### ISSUE TITLE
Outdated: i-doit pro Add-ons -> API (JSON-RPC) -> category fields for data arrays

### ISSUE THREAD

**Issue by jaagut** [i-doit/knowledge-base#343]
Hello,

I was looking at the [category documentation for Operating System](https://kb.i-doit.com/en/i-doit-pro-add-ons/api/category-fields-for-data-arrays.html#operating-system-c__catg__operating_system) and noticed that it may be outdated.

This is because:
- the following fields seem to be missing: `assigned_version_for_report`, `assigned_databases`, `installDate`
- every data type in the docs is `int` (except for `description`), even though it seems like the API might also accept strings for some of those values, e.g., for `assigned_version`.

See here from the administration page:
![image](https://github.com/i-doit/knowledge-base/assets/34797331/e53749dd-982b-4fbd-b8b8-ce69eedc7fc9)

I noticed this because I wondered why every expected request argument is `int`, even though you can insert string values in the web UI, for example in `assigned_version`.

This issue probably also applies to other categories too.

Additional question:
My API client uses `"cmdb.category_info.read"` to find out the data type that is expected for `"cmdb.category.save"`.
In the case of the attribute `assigned_version`, we can see (in the response down below) that 
`response["result"]["assigned_version"]["data"]["type"] = "int"` (and its a `"dialog_plus"`).
So it seems like it only accepts `int`, but we have seen above in the administration that it should also accept `string`. **Is it true, that the API also accepts strings?** Currently, I have no way to test this out. **And how is it possible to know only from API responses, that the data type for `assigned_version` and other attributes is `int` OR `string`?**

Running this RPC
```json
{
    "jsonrpc": "2.0",
    "method": "cmdb.category_info.read",
    "params": {
        "apikey": "...",
        "category": "C__CATG__OPERATING_SYSTEM"
    },
    "id": 1
}
```

also returns

```json
{
    "id": 1,
    "jsonrpc": "2.0",
    "result": {
        "application": {...},
        "application_type": {...},
        "application_priority": {...},
        "assigned_license": {...},
        "assigned_license_key": {...},
        "assigned_it_service": {...},
        "assigned_variant": {...},
        "assigned_version": {
            "title": "Version number",
            "check": {
                "mandatory": null
            },
            "info": {
                "title": "LC__CATG__VERSION_TITLE",
                "type": "dialog_plus",
                "primaryField": false,
                "backwardCompatible": false
            },
            "data": {
                "type": "int",
                "field": "isys_catg_application_list__isys_catg_version_list__id",
                "sourceTable": "isys_catg_version_list",
                "references": [
                    "isys_catg_version_list",
                    "isys_catg_version_list__id"
                ],
                "readOnly": false,
                "joins": [
                    {},
                    {},
                    {}
                ],
                "index": true,
                "select": {}
            },
            "ui": {
                "id": "C__CATG__OPERATING_SYSTEM_VERSION",
                "type": "popup",
                "default": "-1",
                "params": {
                    "p_strPopupType": "dialog_plus",
                    "p_strClass": "input-small",
                    "p_arData": {}
                }
            },
            "format": {
                "callback": [
                    "isys_global_application_export_helper",
                    "applicationAssignedVersion"
                ]
            }
        },
        "assigned_version_for_report": {...},
        "assigned_databases": {...},
        "installDate": {...},
        "description": {...}
    }
}
```

**Comment by MichaelOv** [comment]
Hello @jaagut,

thanks for the info, I will take [Category fields for data arrays](https://kb.i-doit.com/en/i-doit-pro-add-ons/api/category-fields-for-data-arrays.html) down, because it is outdated and it is displayed in i-doit.

![image](https://github.com/i-doit/knowledge-base/assets/59646765/685ad915-a3ff-4383-965a-e7103d89d94d)

The answer to your other Question, this is because you can set and create a dialog+ value.
If you use a `int` it will try to find the dialog+ entry and if you use a `string` it will create a entry.

Hope that helps.

**Comment by jaagut** [comment]
Thank you for your answer. This resolves my issue.
