### ISSUE TITLE
LDAP Debug option missing

### ISSUE THREAD

**Issue by MichaelOv** [i-doit/knowledge-base#368]
https://github.com/i-doit/knowledge-base/blob/d778cfb0a65f9ac97c1a93f0f3ee8331e1639a00/docs/en/system-administration/admin-center.md?plain=1#L61

**Comment by matsica** [comment]
LDAP Debug Option not shown in system settings.
Bug Ticket created: ID-10902

Workaround: Use Expert Settings to toggle setting
